import { articles } from "./permissions/articles";
import { plantGuides } from "./permissions/plant-guides";
import { users } from "./permissions/user";

export const rolesPermissions = {
  ADMIN: new Set([
    ...Object.values(plantGuides),
    ...Object.values(articles),
    ...Object.values(users),
  ]),
  USER: new Set([
    plantGuides.getAllPlantGuides,
    plantGuides.totalPlantGuideCount,
    plantGuides.getPlantGuide,
    articles.getArticleCount,
    articles.getPublishedArticleCount,
    articles.getArticle,
    articles.getAllPublishedArticles,
    articles.incrementLikes,
    articles.incrementArticleViews,
    articles.getArticleAuthor,
    articles.getArticleViews,
    users.getArticleAuthor,
    articles.getArticleViews,
  ]),
  AUTHOR: new Set([
    plantGuides.getAllPlantGuides,
    plantGuides.totalPlantGuideCount,
    plantGuides.getPlantGuide,
    articles.getArticleCount,
    articles.getPublishedArticleCount,
    articles.getArticle,
    articles.getAllPublishedArticles,
    articles.incrementLikes,
    articles.incrementArticleViews,
    articles.getArticleAuthor,
    users.getArticleAuthor,
  ]),
  MODERATOR: new Set([
    plantGuides.getAllPlantGuides,
    plantGuides.totalPlantGuideCount,
    plantGuides.getPlantGuide,
    articles.getArticleCount,
    articles.getPublishedArticleCount,
    articles.getArticle,
    articles.getAllPublishedArticles,
    articles.incrementLikes,
    articles.incrementArticleViews,
    articles.getArticleAuthor,
    users.getArticleAuthor,
  ]),
  GUEST: new Set([
    plantGuides.getAllPlantGuides,
    plantGuides.totalPlantGuideCount,
    plantGuides.getPlantGuide,
    plantGuides.getFeaturedPlantGuides,
    articles.getArticleCount,
    articles.getPublishedArticleCount,
    articles.getArticle,
    articles.getAllPublishedArticles,
    articles.incrementLikes,
    articles.incrementArticleViews,
    articles.getArticleAuthor,
    users.getArticleAuthor,
  ]),
} as const;
