import { articles } from "./permissions/articles";
import { plantGuides } from "./permissions/plant-guides";
import { users } from "./permissions/user";

export const rolesPermissions = {
  admin: new Set([
    ...Object.values(plantGuides),
    ...Object.values(articles),
    ...Object.values(users),
  ]),
  user: new Set([
    plantGuides.getAllPlantGuides,
    plantGuides.totalPlantGuideCount,
    plantGuides.getPlantGuide,
    articles.getArticleCount,
    articles.getPublishedArticleCount,
    articles.getArticle,
    articles.getAllPublishedArticles,
    articles.incrementLikes,
    articles.incrementArticleViews,
    articles.getArticleAuthor,
    users.getArticleAuthor,
  ]),
  author: new Set([
    plantGuides.getAllPlantGuides,
    plantGuides.totalPlantGuideCount,
    plantGuides.getPlantGuide,
    articles.getArticleCount,
    articles.getPublishedArticleCount,
    articles.getArticle,
    articles.getAllPublishedArticles,
    articles.incrementLikes,
    articles.incrementArticleViews,
    articles.getArticleAuthor,
    users.getArticleAuthor,
  ]),
  moderator: new Set([
    plantGuides.getAllPlantGuides,
    plantGuides.totalPlantGuideCount,
    plantGuides.getPlantGuide,
    articles.getArticleCount,
    articles.getPublishedArticleCount,
    articles.getArticle,
    articles.getAllPublishedArticles,
    articles.incrementLikes,
    articles.incrementArticleViews,
    articles.getArticleAuthor,
    users.getArticleAuthor,
  ]),
  guest: new Set([
    plantGuides.getAllPlantGuides,
    plantGuides.totalPlantGuideCount,
    plantGuides.getPlantGuide,
    articles.getArticleCount,
    articles.getPublishedArticleCount,
    articles.getArticle,
    articles.getAllPublishedArticles,
    articles.incrementLikes,
    articles.incrementArticleViews,
    articles.getArticleAuthor,
    users.getArticleAuthor,
  ]),
} as const;
